### ISSUE TITLE
可以考虑同时生成一个数据表结构的md文件。

### ISSUE THREAD

**Issue by flysail** [kkzhilu/Code-Generate#1]
之前在做基于pdm自动生成代码，最近开始做基于数据库生成代码。
之前生成的数据结构文档都是excel的，现在开始转向md文件了。

**Comment by kkzhilu** [comment]
安排！！
基于md文件  把表结构和具体的相关参数都Push出来，清晰明了，是一个很好的建议，我下次更新就弄这个了

感谢~

**Comment by kkzhilu** [comment]
需求已经落实啦~
